### ISSUE TITLE
Errors when trying to make a swap.

### ISSUE THREAD

**Issue by The-Raphie** [CyberAnon1010101/Blockchain-ArbitrageBot#5]
When the bot finds a profitable swap, this happens:
```
Swap Initiated on Uniswap, Checking Price...

Current Block: 62984991
-----------------------------------------
UNISWAP   | WETH/WPOL    | 6718
SUSHISWAP | WETH/WPOL    | 6683

Percentage Difference: 0.52%

Determining Direction...

Potential Arbitrage Direction:

Buy      -->     Uniswap
Sell     -->     Sushiswap

Determining Profitability...

Error: execution reverted: "ds-math-sub-underflow" (action="call", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001564732d6d6174682d7375622d756e646572666c6f770000000000000000000000", reason="ds-math-sub-underflow", transaction={ "data": "0x1f00ca7400000000000000000000000000000000000000000000001552c03c7488df128d000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000d500b1d8e8ef31e21c99d1db9a6444d3adf12700000000000000000000000007ceb23fd6bc0add59e62ac25578270cff1b9f619", "to": "0xedf6066a2b290C185783862C7F4776A2C8077AD1" }, invocation=null, revert={ "args": [ "ds-math-sub-underflow" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.13.2)
    at makeError (/home/the_raphie/Arbitrage-Bot/node_modules/ethers/lib.commonjs/utils/errors.js:129:21)
    at getBuiltinCallException (/home/the_raphie/Arbitrage-Bot/node_modules/ethers/lib.commonjs/abi/abi-coder.js:105:37)
    at AbiCoder.getBuiltinCallException (/home/the_raphie/Arbitrage-Bot/node_modules/ethers/lib.commonjs/abi/abi-coder.js:206:16)
    at Interface.makeError (/home/the_raphie/Arbitrage-Bot/node_modules/ethers/lib.commonjs/abi/interface.js:787:47)
    at staticCallResult (/home/the_raphie/Arbitrage-Bot/node_modules/ethers/lib.commonjs/contract/contract.js:249:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async staticCall (/home/the_raphie/Arbitrage-Bot/node_modules/ethers/lib.commonjs/contract/contract.js:219:24)
    at async Proxy.getAmountsIn (/home/the_raphie/Arbitrage-Bot/node_modules/ethers/lib.commonjs/contract/contract.js:259:20)
    at async determineProfitability (/home/the_raphie/Arbitrage-Bot/bot.js:176:22)
    at async Proxy.<anonymous> (/home/the_raphie/Arbitrage-Bot/bot.js:43:28) {
  code: 'CALL_EXCEPTION',
  action: 'call',
  data: '0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001564732d6d6174682d7375622d756e646572666c6f770000000000000000000000',
  reason: 'ds-math-sub-underflow',
  transaction: {
    to: '0xedf6066a2b290C185783862C7F4776A2C8077AD1',
    data: '0x1f00ca7400000000000000000000000000000000000000000000001552c03c7488df128d000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000d500b1d8e8ef31e21c99d1db9a6444d3adf12700000000000000000000000007ceb23fd6bc0add59e62ac25578270cff1b9f619'
  },
  invocation: {
    method: 'getAmountsIn',
    signature: 'getAmountsIn(uint256,address[])',
    args: Result(2) [ 393344457925749314189n, [Result] ]
  },
  revert: {
    signature: 'Error(string)',
    name: 'Error',
    args: [ 'ds-math-sub-underflow' ]
  },
  shortMessage: 'execution reverted: "ds-math-sub-underflow"'
}

Error occured while trying to determine profitability...

This can typically happen because of liquidity issues, see README for more information.

No Arbitrage Currently Available

``` 

I'm using polygon and I have more than enough in my balance to cover the gas fees, so why could this be happening?

**Comment by Dababebeaut** [comment]
Hello @The-Raphie 
I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Arbitrage-Bot Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!
